import React from 'react';
import { useLanguage } from '@/contexts/LanguageContext';
import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';
import { cn } from '@/lib/utils';

interface ExportButtonProps {
  originalImage: string | null;
  gradcamImage: string | null;
  prediction: string | null;
  confidence: number | null;
  disabled?: boolean;
}

const ExportButton: React.FC<ExportButtonProps> = ({
  originalImage,
  gradcamImage,
  prediction,
  confidence,
  disabled,
}) => {
  const { t, isRTL } = useLanguage();

  const handleExport = async () => {
    if (!originalImage || !gradcamImage) return;

    // Create canvas for combined export
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    // Load images
    const loadImage = (src: string): Promise<HTMLImageElement> => {
      return new Promise((resolve, reject) => {
        const img = new Image();
        img.crossOrigin = 'anonymous';
        img.onload = () => resolve(img);
        img.onerror = reject;
        img.src = src;
      });
    };

    try {
      const [origImg, gradImg] = await Promise.all([
        loadImage(originalImage),
        loadImage(gradcamImage),
      ]);

      // Set canvas size (2 images side by side + info section)
      const imgWidth = Math.max(origImg.width, gradImg.width, 300);
      const imgHeight = Math.max(origImg.height, gradImg.height, 300);
      const padding = 20;
      const infoHeight = 80;

      canvas.width = imgWidth * 2 + padding * 3;
      canvas.height = imgHeight + infoHeight + padding * 3;

      // Background
      ctx.fillStyle = '#f8fafc';
      ctx.fillRect(0, 0, canvas.width, canvas.height);

      // Draw images
      ctx.drawImage(origImg, padding, padding, imgWidth, imgHeight);
      ctx.drawImage(gradImg, imgWidth + padding * 2, padding, imgWidth, imgHeight);

      // Labels
      ctx.fillStyle = '#1e3a5f';
      ctx.font = 'bold 14px Inter, sans-serif';
      ctx.fillText('Original Image', padding, imgHeight + padding * 2 + 20);
      ctx.fillText('Grad-CAM Heatmap', imgWidth + padding * 2, imgHeight + padding * 2 + 20);

      // Prediction info
      const predictionText = `Prediction: ${prediction} | Confidence: ${confidence?.toFixed(1)}%`;
      ctx.font = 'bold 16px Inter, sans-serif';
      ctx.fillText(predictionText, padding, imgHeight + padding * 2 + 50);

      // MicroCalc branding
      ctx.font = '12px Inter, sans-serif';
      ctx.fillStyle = '#64748b';
      ctx.fillText('Generated by MicroCalc - Breast Cancer Microcalcification Detection', padding, imgHeight + padding * 2 + 70);

      // Download
      const link = document.createElement('a');
      link.download = `microcalc-analysis-${Date.now()}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
    } catch (error) {
      console.error('Export failed:', error);
    }
  };

  return (
    <Button
      onClick={handleExport}
      disabled={disabled || !originalImage || !gradcamImage}
      variant="outline"
      className={cn("gap-2", isRTL && "flex-row-reverse")}
    >
      <Download className="h-4 w-4" />
      {t('results.exportPNG')}
    </Button>
  );
};

export default ExportButton;